features:
  observation.images.exterior_image:
    dtype: video
    shape: [480, 640, 3]
    names: [height, width, channels]
  observation.images.wrist_image:
    dtype: video
    shape: [480, 640, 3]
    names: [height, width, channels]
  state:
    dtype: float32
    shape: [7]
    names: [ee_pose_and_gripper_width]
  actions:
    dtype: float32
    shape: [7]
    names: [delta_ee_pose_and_gripper_action]
